### ISSUE TITLE
Europa raid doesn't show up

### ISSUE THREAD

**Issue by Azriael2** [NthMetal/gbraidfinder#22] opened 2023-03-27 06:31 UTC
Europa (Impossible) raid doesn't show up at all, which is weird considering we have boosted water raids :|

**Comment by NthMetal** [comment] 2023-03-27 13:56
I think this is due to a low volume of raids. Even other raidfinders aren't getting very many.
Example: 
![image](https://user-images.githubusercontent.com/7328874/227956713-28c278f5-87eb-4e51-b504-f4014d686db2.png)

Additionally if you check the stats page, europa seems to have dropped in frequency on march 14th. I don't know why this is the case, it may be twitter related, but i'm not sure. ~~It might be because dread barrage so people aren't running it as much? If I were to guess it's because people are choosing to solo it instead because avatar is also really low and dark guild wars is coming up.~~

Here is an image of all the magna 2 raids (you can view this too on the stats page for more details):
![image](https://user-images.githubusercontent.com/7328874/227959862-1634cac4-6197-459f-aa58-54be87abdf61.png)

Edit: I think actually it may be an issue with getting the tweet into raidfinders. I don't know why but tweetdeck seems to be the only platform that has recent tweets:

![image](https://user-images.githubusercontent.com/7328874/227962165-2147eaa5-5704-49c0-9bb9-e662fc1e3d8f.png)

**Comment by YdenMkII** [comment] 2023-03-30 03:48
The issue is that those raids were marked as sensitive content and you need to disable that filter in your search settings since that type of content is hidden by default.  If you go into Settings > Privacy > Content you see > Search > and tick the hide sensitive content box, those raids stop showing up in tweetdeck and you get this message instead.  
![Screenshot 2023-03-29 at 20-46-51 TweetDeck](https://user-images.githubusercontent.com/128202448/228723697-ccb01494-6112-4c2e-9fe8-631226d7e574.png)
Not sure if this raid tracker uses an account to scrape, but if so that setting needs to be disabled for them to be searchable.

**Comment by NthMetal** [comment] 2023-03-30 03:53
Oh ok that makes sense. I was trying to figure out the cause of the problem, but that seems like it could be it.

I'll diagnose further and work on finding a solution soon.

**Comment by NthMetal** [comment] 2023-04-08 17:52
this should be fixed now
let me know if there are further issues

**Closed as completed by NthMetal** 2023-04-08 17:52 UTC
